[package]
name = "setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
electrum-client="0.10.2"
bitcoincore-rpc="0.15.0"
bitcoin={version="0.28.1",features=["rand","std"]}